language: java
jdk:
 - openjdk8
services:
  - mysql
before_script:
  - cp config/database.yml.travis config/database.yml
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bankaccount;'
install:
- mvn install -P prod -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
- mvn clean verify