# Server
server:
  port: 3001

# DataSource
spring:
  datasource:
    url:jdbc:h2:mem: bankaccount
    driverClassName: org.h2.Driver
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect